/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2017-04-07 01:12:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import yishan.Po.Goods;

public final class PDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1337070341442L));
    _jspx_dependants.put("jar:file:/D:/javaEE/javaEEWorkSpace2/12/yishan/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("      \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Details</title>\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/Details.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"js/jquery-2.2.2.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,Chrome=1\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=9\" />\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"http://apps.bdimg.com/libs/html5shiv/3.7/html5shiv.min.js\"></script>\r\n");
      out.write("    <script src=\"http://apps.bdimg.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\" id=\"header\">\r\n");
      out.write("    <div class=\"navbar-default\" id=\"header-top\">\r\n");
      out.write("        <div id=\"top-left\">\r\n");
      out.write("            <ul class=\"nav nav-pills\" role=\"tablist\">\r\n");
      out.write("                <li role=\"presentation\" class=\"active\"><a href=\"#\">后台中心</a></li>\r\n");
      out.write("                <li role=\"presentation\"><a href=\"#\">退出</a></li>\r\n");
      out.write("                <li role=\"presentation\"><a href=\"#\">登录</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"top-right\">\r\n");
      out.write("            <ul class=\"nav nav-pills\" role=\"tablist\">\r\n");
      out.write("                <li role=\"presentation\"><a href=\"IssueHeart.jsp\">发布物品</a></li>\r\n");
      out.write("                  <li role=\"presentation\"><a href=\"#\">需求发布</a></li>\r\n");
      out.write("                  <li role=\"presentation\"><a href=\"PersonalGoodsMagager.do\">物品管理</a></li>\r\n");
      out.write("                  <li role=\"presentation\"><a href=\"#\">个人交易</a></li>\r\n");
      out.write("                <li role=\"presentation\">\r\n");
      out.write("                    <div class=\"dropdown\">\r\n");
      out.write("                        <button class=\"btn btn-default dropdown-toggle\" type=\"button\" id=\"dropdownMenu1\" data-toggle=\"dropdown\">\r\n");
      out.write("                            联系我们\r\n");
      out.write("                            <span class=\"caret\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <ul class=\"dropdown-menu\" role=\"menu\" aria-labelledby=\"dropdownMenu1\">\r\n");
      out.write("                            <li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"#\">电话：*************</a></li>\r\n");
      out.write("                            <li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"#\">邮箱：*************</a></li>\r\n");
      out.write("                            <li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"#\">传真：*************</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"header-bottom\" class=\"row\">\r\n");
      out.write("    <div id=\"logo\" class=\"col-md-4 col-md-offset-1\" ></div>\r\n");
      out.write("    <div id=\"sousou\" class=\"col-md-4 col-md-offset-2\">\r\n");
      out.write("        <form class=\"form-horizontal\" action=\"\" method=\"post\">\r\n");
      out.write("            <div class=\"input-group\">\r\n");
      out.write("                <input type=\"text\" name=\"cond\" class=\"form-control\" style=\"border:#F52B00 2px solid\" placeholder=\"Search for...\">\r\n");
      out.write("                <span class=\"input-group-btn\">\r\n");
      out.write("        <input class=\"btn btn-default btn-warning\"  type=\"submit\" value=\"搜索\">\r\n");
      out.write("      </span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        <p class=\"navbar\"><a href=\"\">潮流T恤</a>|<a href=\"\">时尚女鞋</a>|<a href=\"\">短裤</a>|<a href=\"\">半身裙</a>|<a href=\"\">行车记录仪</a>|<a href=\"\">新款</a>|<a href=\"\">男鞋</a>|<a href=\"\">耳机</a>|<a href=\"\">时尚</a>|<a href=\"\">女包</a>|<a href=\"\">更多➤</a></p>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<nav class=\" navbar-default\" style=\"list-style: none\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li class=\"dropdown navbar-brand\" style=\"margin-left:8%\" id=\"shouye\"><a href=\"\"><i class=\"glyphicon glyphicon-home\"></i>首页</a>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h4>服饰</h4>\r\n");
      out.write("                    <table border=\"0\">\r\n");
      out.write("                        <tr><td>女装</td><td>男装</td><td>儿童装</td><td>更多</td></tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <h4>手机数码</h4>\r\n");
      out.write("                    <table border=\"0\">\r\n");
      out.write("                        <tr><td>Iphone手机</td><td>国产手机</td><td>手机配件</td><td>更多</td></tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <h4>电脑配件</h4>\r\n");
      out.write("                    <table border=\"0\" >\r\n");
      out.write("                        <tr><td>笔记本配件</td><td>台式机配给</td><td>更多</td></tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"navbar-brand \">最新发布\r\n");
      out.write("                <div >\r\n");
      out.write("                </div></li>\r\n");
      out.write("            <li class=\"navbar-brand \">最新需求\r\n");
      out.write("                <div >\r\n");
      out.write("                </div></li>\r\n");
      out.write("            <li class=\"navbar-brand \">物易物\r\n");
      out.write("                <div>\r\n");
      out.write("                </div></li>\r\n");
      out.write("            <li class=\"navbar-brand \">我要留言\r\n");
      out.write("                <div>\r\n");
      out.write("                </div></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"row\" style=\"margin-top: 20px;height: 400px\">\r\n");
      out.write("        <div class=\"col-md-5 col-md-offset-2 thumbnail\" style=\"height: 400px\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.paddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-2\">\r\n");
      out.write("            <div style=\"margin-top: 50px\">\r\n");
      out.write("                <span style=\"font-size: medium;color: #2b669a\">物品名称：");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.goodsname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span><span></span><br><br>\r\n");
      out.write("                <span style=\"font-size: medium;color: #2b669a\">物品描述：");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.discription}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span><span></span><br><br>\r\n");
      out.write("                <span style=\"font-size: medium;color: #2b669a\">联系方式：");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.tel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span><span></span><br><br>\r\n");
      out.write("                <span style=\"font-size: medium;color: #2b669a\">交易状态：");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.discription}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span><span></span><br><br>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-offset-1 col-md-2\" style=\"margin-top: 40px\">\r\n");
      out.write("                        <div class=\"btn btn-lg btn-info\"><a href=\"goodsDelet/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.PID }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".do\">下架</a></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-offset-6 col-md-3\" style=\"margin-top: 40px\">\r\n");
      out.write("                        <div class=\"btn btn-lg btn-info\"><a href=\"goodsDelet/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.PID }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".do\">修改</a></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function (){\r\n");
      out.write("        $(\"#shouye\").hover(function(){\r\n");
      out.write("            $(this).addClass(\"liHover\");\r\n");
      out.write("            $(this).find(\"div:hidden\").show();\r\n");
      out.write("        },function (){\r\n");
      out.write("            $(this).find(\"div:visible\").hide();\r\n");
      out.write("            $(this).removeClass(\"liHover\");\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
